### ISSUE TITLE
MVPリリース　レビュー依頼

### ISSUE THREAD

**Issue by ken55ty** [ken55ty/stay_with_mu#153]
お世話になっております。
卒業試験のMVPリリース依頼を提出いたします。
お忙しいところ恐れ入りますが、ご確認のほどよろしくお願い致します。
## 各種情報
サービス名: STAY with MU（ステイウィズミュー）
サービスURL: https://www.stay-with-mu.com/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] 新規登録
- [x] ログイン
- [x] MU作成機能
- [x] MU一覧
- [x] MU検索
- [x] MUソート機能
- [x] MU詳細
- [x] MU編集・削除機能
- [x] MUレベルアップ機能
- [x] Xシェア機能
- [x] メモリー追加機能
- [x] メモリー編集・削除機能
- [x] メモリータグ機能
- [x] コメント機能
- [x] コメント編集・削除機能
- [x] いいね機能
- [x] プロフィール
- [x] パスワードリセット機能
## 必要なページ
- [x] トップページ
- [x] 新規登録ページ
- [x] ログインページ
- [x] MU一覧ページ
- [x] MU作成ページ
- [x] MU詳細ページ（メモリー・コメントも表示）
- [x] MU編集ページ
- [x] プロフィールページ（作成したMU一覧・いいねしたMU一覧）
- [x] プロフィール編集ページ
- [x] 利用規約ページ
- [x] プライバシーポリシーページ
- [x] パスワードリセットページ

## READMEレビュー時から変更した機能
- 楽曲のジャケット写真を保存して表示する予定でしたが、iframeの埋め込みに変更しました。
- MU（楽曲）作成時に出会った日時と状況を任意で入力する仕様にする予定でしたが、初期の利用ハードルを下げる目的で廃止しました。
- MUのレベルによって文字の色が変化する機能を追加しました。
## 本リリース時に実装したい機能
- [ ] ユーザーメダル機能
- [ ] Google認証ログイン
- [ ] リメンバーミー
- [ ] メモリー非表示機能
- [ ] 今日のお題レコメンド機能
- [ ] ユーザーフォロー機能
- [ ] いいね数・メモリー数・コメント数によるソートを追加
- [ ] お知らせ機能
- [ ] （余力があれば）プレイリスト作成機能

## サービスイメージがわかるようなスクリーンショット等
**トップページ**
![Image](https://github.com/ken55ty/stay_with_mu/assets/142506480/f2262a04-6575-4504-b619-997ef2dfb2a3)

**みんなのMU一覧ページ**

![Image](https://github.com/ken55ty/stay_with_mu/assets/142506480/39549a76-d950-49a8-8035-d292fee6c4e3)

**MU詳細（メモリーのタブ）**
![Image](https://github.com/ken55ty/stay_with_mu/assets/142506480/03694ad2-3ac6-4fe2-958a-e51f8fadb37d)

**MU詳細（コメントのタブ）**
![Image](https://github.com/ken55ty/stay_with_mu/assets/142506480/25387199-21a4-4d01-ad2c-7bffbe08c44d)

**マイページ（つくったMUのタブ）**
![Image](https://github.com/ken55ty/stay_with_mu/assets/142506480/379b36a5-8d5b-45d9-b4a1-f2d4f7309b53)

**マイページ（いいねしたMUのタブ）**
![Image](https://github.com/ken55ty/stay_with_mu/assets/142506480/7c5a1a37-3f4f-4038-86e8-204f5e5e70c9)

**MU作成（検索結果）**
![Image](https://github.com/ken55ty/stay_with_mu/assets/142506480/b58aaf80-daea-4358-9a5a-5379142c292a)

以上、ご確認のほどよろしくお願いします。

**Comment by Tsuchiya2** [comment]
MUレベルアップ機能

↑の機能はどのような操作を行えば確認できるかを教えていただけますでしょうか。

**Comment by ken55ty** [comment]
わかりにくくて申し訳ございません。
メモリーを追加すると文字数に応じてレベルが上がります。(最初のレベルアップには最低でも5文字必要です。）
メモリー追加は非同期処理のため、ページ更新が必要になっております。
お手数ですがご確認のほどよろしくお願いします。

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。

**Comment by ken55ty** [comment]
ありがとうございます！
