### ISSUE TITLE
中間報告レビュー

### ISSUE THREAD

**Issue by tmtkzk0823** [ken55ty/stay_with_mu#179]
Webアプリの中間報告ありがとうございました！
以下、レビュー内容になりますのでご確認ください。

### 技術
- scaffoldで作成したと思われてしまうコメントアウトが残っているので、削除しておくといいかと思います。
- この後は本リリースに向けて実装していくかと思いますが、曲名、アーティスト名の検索に「オートコンプリート」があると、アプリとして完成度が増すかと思ったので、優先してそちらを実装しても良さそうです。（API使用して取得しているかと思いますが、JSとうまく組み合わせでデータを取得できるような[記事](https://qiita.com/hirapg_1123/items/b447ce465ca8103e6f4e)があったので共有しておきますね。）

### ユーザビリティ
ユーザビリティはかなり綺麗にできていると思います。
細かい点で1点だけ
- メモリーのタグをを追加する時に、要素全体ではなく、チェックボックスをクリックしないと設定できなそうですので、ご確認をお願いします。

以上です！
全体的に良くできていて、ユーザビリティの高いアプリケーションだと思いました。
技術は、本リリース時に実装予定の機能を実装できればしっかりアピールできると思います。

また上記レビューに関して、質問などありましたらスレッドに記載いただいてご連絡ください！

**Comment by ken55ty** [comment]
レビューいただきありがとうございます！
引き続き本リリースに向け頑張ります！
