### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by ken55ty** [ken55ty/stay_with_mu#45]
### 実装予定の機能(MVP)
- [ ] 新規登録
- [ ] ログイン
- [ ] MU作成機能
- [ ] MU一覧
- [ ] MU検索
- [ ] MUソート機能
- [ ] MU詳細
- [ ] MU編集・削除機能
- [ ] MUレベルアップ機能
- [ ] Xシェア機能
- [ ] メモリー追加機能
- [ ] メモリー編集・削除機能
- [ ] メモリータグ機能
- [ ] コメント機能
- [ ] コメント編集・削除機能
- [ ] いいね機能
- [ ] プロフィール
- [ ] パスワードリセット機能
### 必要なページ
- [ ] トップページ
- [ ] 新規登録ページ
- [ ] ログインページ
- [ ] MU一覧ページ
- [ ] MU作成ページ
- [ ] MU詳細ページ（メモリー・コメントも表示）
- [ ] MU編集ページ
- [ ] プロフィールページ（作成したMU一覧・いいねしたMU一覧）
- [ ] プロフィール編集ページ
- [ ] 利用規約ページ
- [ ] プライバシーポリシーページ
- [ ] パスワードリセットページ

**Comment by Tsuchiya2** [comment]
概ね良いかと思います。LGTMです。

**Comment by ken55ty** [comment]
ありがとうございます！
